### ISSUE TITLE
readme和paper里的结果不一样

### ISSUE THREAD

**Issue by lssshuang** [AnselCmy/MetaR#12]
作者您好，我看到您论文里结果
![1701397900722](https://github.com/AnselCmy/MetaR/assets/119313579/575a363f-6575-45e8-bf66-17664e36f8f0)
和readme写的并不一致
![1701397999841](https://github.com/AnselCmy/MetaR/assets/119313579/160bf980-139a-425c-b37f-d0d575cd0ba0)
，是改了哪些地方吗？

**Comment by AnselCmy** [comment]
有一些参数的调整，可以参考本仓库具体的代码进行复现。
