### ISSUE TITLE
the method of limiting the candidate entities

### ISSUE THREAD

**Issue by JiyaoWei** [AnselCmy/MetaR#2]
Hello, AnselCmy

Can you help me understand the method of limiting the candidate entities, in "One-Shot Relational Learning for Knowledge Graphs". Many people cited your paper, but they have not given a specific parameters.

How did you make specific restrictions in your experiment? Can you show your code for generating the candidate set?

Looking forward to your reply!

**Comment by AnselCmy** [comment]
Type constrain is applied for limiting the candidate entities, and you can refer to the example code in OpenKE (https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/benchmarks/FB15K237/n-n.py) for details of generating such constrain.
