### ISSUE TITLE
The experimental results are different between the original paper and GitHub

### ISSUE THREAD

**Issue by YanpingWu12138** [AnselCmy/MetaR#3]
Hello, AnselCmy
     
Can you help me understand why the experimental results in your GitHub are higher than those in your original paper?
Did you make improvements after you published the paper or there is a new paper here?

**Comment by AnselCmy** [comment]
Thanks! We finetuned the hyper-parameters after this paper was accepted. There is no significant improvement in the method, and it's not a new paper here.
