### ISSUE TITLE
The number of train

### ISSUE THREAD

**Issue by LemonQC** [AnselCmy/MetaR#4]
![image](https://user-images.githubusercontent.com/30914380/117395162-07d7c300-af2a-11eb-919c-94c45d27aa40.png)
While I read the data， 772 in train_tasks_in_train.json

**Comment by AnselCmy** [comment]
Thanks for trying our source code. For the file "train_tasks_in_train.json" of NELL and Wiki, the lengths indeed are 342 and 772. However, we ignore small training tasks which have no more than 10 triples (implemented in line 34 of "data_loader.py"), so the final statistics are 321 and 589.
