### ISSUE TITLE
MetaR object has no attribute 'relation_learner'

### ISSUE THREAD

**Issue by Baojiankun** [AnselCmy/MetaR#5]
![metaR](https://user-images.githubusercontent.com/61734286/161463582-b84213f9-df04-4c1b-9942-def08b137a9c.png)
Please how to solve this problem？
What is 'relation_learner' ?

**Comment by AnselCmy** [comment]
I've tried the code, and there is no problem. Did you change the code or use your own dataset? Could you please give more details? Thanks!
