### ISSUE TITLE
Why are you dealing with xiong's dataset? What is the role of prepare.py?

### ISSUE THREAD

**Issue by EchoJZ** [AnselCmy/MetaR#6]
Hello! Thanks for your code! I have some questions:
(1) Why are you dealing with xiong's dataset? I saw some dataset with in_train tail, but I dont understand why.
(2) What is the role of prepare.py?

thank you very much!

**Comment by AnselCmy** [comment]
Thanks for reading our code! For your question:

1. The "in_train" and "pre_train" settings are two different training settings as described in our paper. In short, in the "in_train" setting, we transform triples in the background KG into our training tasks, and more details can be found in our paper. 
2. As described in README, we use prepare.py to transform the data format from original datasets into the format of our code.
