### ISSUE TITLE
Entity.TransE在哪里？

### ISSUE THREAD

**Issue by With-JS** [AnselCmy/MetaR#7]
我下载的数据里没有entity.Transe文件怎么办呢
![image](https://user-images.githubusercontent.com/105687530/168752142-a7708c3e-4a3b-4338-b207-64a59b527fb3.png)

**Comment by AnselCmy** [comment]
感谢关注我们的工作，你可以在https://github.com/xwhan/One-shot-Relational-Learning 的README中，找到“Pre-trained embeddings”部分，下载相应的实体向量。
